version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - API_PRIVATE=${API_PRIVATE}
      - GCP_URL=${GCP_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
